services:
  - type: web
    name: iris-predictor
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app_noplots:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: SECRET_KEY
        generateValue: true
